# Generated by Django 3.1 on 2021-08-27 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='created_At',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='created_At',
            new_name='created_at',
        ),
    ]
